### ISSUE TITLE
allow to specify the task filepath to execute

### ISSUE THREAD

**Issue by zoocide** [zoocide/pts#4]
Запуск задач, указанием пути к их конфигурацонным файлам.
При этом переменная $name должна остаться прежней.

Task:
- Нужно поменять $name. Сейчас name = short_id. А должна содержать basename(short_id).
Остальное все не мешает.

TaskDB:
- get_task($tid) должен выдавать задачи ожидаемым образом.

Сейчас указание задач выглядит следующим образом:
- возможно указывать только имена задач, которые лежат непосредственно в директориях -T.

**Comment by zoocide** [comment]
### Вариант 1:
действовать аналогично шеллу:
- -T - аналог path
- имена без '/ ' искать непосредственно в -T
- имена с '/' трактовать как путь к файлу

#### плюсы:
- привычное использование. Задачи вызываются аналогичным образом, как команды в шелле.
#### минусы:

**Comment by zoocide** [comment]
### Вариант 2:
- имена, начинающиеся с './' или полные пути считать заданием файла;
- остальные искать в -T;
#### плюсы:
- можно иметь сложную структуру системных задач и выполнять их откуда угодно.
#### минусы:
- указывать файлы в директории придется ./dir/task. Неочевидно, что, если есть в текущей директории dir/task, то pts dir/task будет искать его где-то в другом месте
- определение полного пути на разных платформах может быть разным (нечего указывать полные пути в кросс-платформенных задачах)
- системные задачи сложной структуры не отображаются в списке --list

**Comment by zoocide** [comment]
@kaniandr отметь, какой вариант больше нравится

**Comment by kaniandr** [comment]
Я правильно понимаю, что в первом случае:

```bash
pts -T path t #вызов из path
pts -T path t1/t #вызов из текущей директории
```

Во втором варианте при этом всегда вызов из path. Здесь получается тоже неестественно, что будет поиск `t` в `path`. При этом второй вариант заставляет всегда писать явно `./...`.

А если он не найдет в `path`, то будет искать в текущей директории или нет?

А если указано несколько path и есть одинаковые задачи?

**Comment by zoocide** [comment]
Правильно понимаешь, так bash работает. Поэтому, чтобы запустить программу из текущей директории и приходится писать ./proga.
Поиск выполняется либо в текущей директории, либо в path.
Всегда можно добавить текущую директорию в path, если хочется искать и там и там.
В обоих вариантах, если в path в разных местах есть задачи с одинаковым именем, то будет взята первая найденная.

**Comment by kaniandr** [comment]
Я как-то не задумывался на эту тему. Наверное, потому что не запускаю команды в виде path/name из bash (всегда пишу ./ в начале), а может просто не предавал этому значение.

Тогда я согласен, первый вариант лучше подходит.

**Comment by zoocide** [comment]
Тут возникла проблема с переменной name. По хорошему она должна бы остаться прежней, но когда указываешь dir/task, в выводе пишется:
````bash
ok.............task
````
а хотелось бы
````bash
ok.............dir/task
````
Возможно стоит поменять переменные:
````bash
name = dir/task
basename = task
````
или
````bash
name = task
name_group = dir 
# ok.............[dir] task
````

**Comment by zoocide** [comment]
наверное, не нужно вводить переменную, а просто всегда писать путь, если он есть:
````bash
> pts dir/task
# name = task
ok.............[dir] task
````

**Comment by zoocide** [comment]
В итоге:
Выбран [Вариант 1](https://github.com/zoocide/pts/issues/4#issuecomment-770102767).
У класса `Task` добавятся методы:
- `name_prefix()`, по умолчанию равен:
  - 'dir/' для задачи dir/task.
  - '' для задачи task.
- `set_name_prefix('new_prefix')`
- `fullname() #fullname = 'name_prefix'.'name'`

В выводе pts будет указываться `fullname`
